config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :payment_methods
  resources :products
  resources :customers
  resources :suppliers
  resources :categories
  devise_for :admins
  resources :admins
  get 'dashboard/index'
  root 'dashboard#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:date_ordered, :customer_id, :shipping_fee, :payment_method_id, :verified, :delivery_date)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_ordered %>
    <%= form.datetime_select :date_ordered %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :shipping_fee %>
    <%= form.text_field :shipping_fee %>
  </div>

  <div class="field">
    <%= form.label :payment_method_id %>
    <%= form.text_field :payment_method_id %>
  </div>

  <div class="field">
    <%= form.label :verified %>
    <%= form.check_box :verified %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.datetime_select :delivery_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1><hr>
<div class="jumbotron">
  <div class="overflow">

    <table>
      <thead>
        <tr>
          <th>Date ordered</th>
          <th>Customer</th>
          <th>Shipping fee</th>
          <th>Payment method</th>
          <th>Verified</th>
          <th>Delivery date</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.date_ordered %></td>
            <td><%= transaction.customer %></td>
            <td><%= transaction.shipping_fee %></td>
            <td><%= transaction.payment_method %></td>
            <td><%= transaction.verified %></td>
            <td><%= transaction.delivery_date %></td>
            <td><%= link_to 'Show', transaction %></td>
            <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
            <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Transaction', new_transaction_path %>
  </div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date ordered:</strong>
  <%= @transaction.date_ordered %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @transaction.customer %>
</p>

<p>
  <strong>Shipping fee:</strong>
  <%= @transaction.shipping_fee %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @transaction.payment_method %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @transaction.verified %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @transaction.delivery_date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>